name: Build

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd ${{ github.workspace }}
          bash build.bash
