name: Workflow

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 480
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build
        id: Build
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${{ github.workspace }}:/openvslam-ubuntu-package"
          shell: /bin/bash
          run: |
            cd /openvslam-ubuntu-package
            sed -i s/sudo//g *.bash
            ./build.bash
            ./pack.bash
            mv /openvslam-ubuntu-package.deb /openvslam-ubuntu-package/openvslam-community-arm64.deb
      - name: Upload Deb File
        uses: actions/upload-artifact@v2
        with:
          name: openvslam-community-arm64.deb
          path: ${{ github.workspace }}/openvslam-community-arm64.deb
  Test:
    needs: Build
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Download Deb File
        uses: actions/download-artifact@v2
        with:
          name: openvslam-community-arm64.deb
          path: ~
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Install
        id: Install
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "/home/runner/work/openvslam-ubuntu-package/openvslam-community-arm64.deb:/ws"
          shell: /bin/bash
          run: |
            cd /ws
            sudo apt-get update
            sudo apt install ./openvslam-community-arm64.deb
            git clone https://github.dev/m2-farzan/openvslam-ubuntu-package
            cd openvslam-ubuntu-package
            sed -i s/sudo//g *.bash
            ./test.bash
