name: Workflow

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd ${{ github.workspace }}
          ./build.bash
      - name: Pack
        run: |
          cd ${{ github.workspace }}
          ./pack.bash
      - name: Upload Deb File
        uses: actions/upload-artifact@v2
        with:
          name: openvslam-community.deb
          path: ${{ github.workspace }}.deb
  Test:
    needs: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Download Deb File
        uses: actions/download-artifact@v2
        with:
          name: openvslam-community.deb
          path: ~
      - name: Install
        run: |
          sudo apt-get update
          sudo apt install /home/runner/work/openvslam-ubuntu-package/openvslam-ubuntu-package/openvslam-ubuntu-package.deb
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          cd ${{ github.workspace }}
          ./test.bash
